apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-rhtap-devfile-multi-component-zx8o
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-rhtap-devfile-multi-component-zx8o
    app.kubernetes.io/part-of: mc-two-scenarios
  name: devfile-sample-python-basic-rhtap-devfile-multi-component-zx8o
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-rhtap-devfile-multi-component-zx8o
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-rhtap-devfile-multi-component-zx8o
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-zxgv-tenant/mc-two-scenarios/devfile-sample-python-basic-rhtap-devfile-multi-component-zx8o@sha256:9faa2e3f41d11703466af38383a0e0eaef9d1e432aac43df7abba3412c0d3e74
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
